# Generated by Django 5.1.3 on 2024-11-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('planet', models.CharField(max_length=100)),
                ('sample_type', models.CharField(choices=[('ROCK', 'Rock'), ('SOIL', 'Soil'), ('LIQUID', 'Liquid'), ('GAS', 'Gas'), ('ICE', 'Ice'), ('ORGANIC', 'Organic')], max_length=20)),
                ('date_collected', models.DateField()),
                ('description', models.TextField()),
                ('mass', models.FloatField(help_text='Mass in grams')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_collected'],
            },
        ),
    ]
